export default [
  {
    timestamp: new Date().toUTCString(),
    nozzle_id: 'N-11',
    plant: 'P1',
    machine: 'P1M1',
    reject_sum_percent: 0.034,
    reject_sum: 1,
    reject_factor: 0.05,
    picks: { cumulative_count: 133 },
    placements: { cumulative_count: 833 },
  },
  {
    timestamp: new Date().toUTCString(),
    nozzle_id: 'N-12',
    plant: 'P1',
    machine: 'P1M2',
    reject_sum_percent: 0.014,
    reject_sum: 3,
    reject_factor: 0.02,
    picks: { cumulative_count: 133 },
    placements: { cumulative_count: 833 },
  },
  {
    timestamp: new Date().toUTCString(),
    nozzle_id: 'N-13',
    plant: 'P1',
    machine: 'P1M3',
    reject_sum_percent: 0.044,
    reject_sum: 4,
    reject_factor: 0.06,
    picks: { cumulative_count: 133 },
    placements: { cumulative_count: 833 },
  },
  {
    timestamp: new Date().toUTCString(),
    nozzle_id: 'N-21',
    plant: 'P2',
    machine: 'P2M1',
    reject_sum_percent: 0.034,
    reject_sum: 4,
    reject_factor: 0.003,
    picks: { cumulative_count: 522 },
    placements: { cumulative_count: 822 },
  },
  {
    timestamp: new Date().toUTCString(),
    nozzle_id: 'N-22',
    plant: 'P2',
    machine: 'P2M2',
    reject_sum_percent: 0.024,
    reject_sum: 2,
    reject_factor: 0.04,
    picks: { cumulative_count: 101 },
    placements: { cumulative_count: 102 },
  },
];
