export default [
  {
    nozzle_id: '1-BB',
    timestamp: new Date().toUTCString(),
    plant: 1,
    machine: 1,
    reject_sum_percent: 0.034,
    reject_sum: 1,
    reject_factor: 0.05,
    picks: { cumulative_count: 133 },
    placements: { cumulative_count: 833 },
  },
  {
    nozzle_id: '1-CC',
    timestamp: new Date().toUTCString(),
    plant: 2,
    machine: 2,
    reject_sum_percent: 0.044,
    reject_sum: 4,
    reject_factor: 0.06,
    picks: { cumulative_count: 133 },
    placements: { cumulative_count: 833 },
  },
  {
    nozzle_id: '1-DD',
    timestamp: new Date().toUTCString(),
    plant: 1,
    machine: 2,
    reject_sum_percent: 0.014,
    reject_sum: 3,
    reject_factor: 0.02,
    picks: { cumulative_count: 133 },
    placements: { cumulative_count: 833 },
  },
  {
    nozzle_id: '1-EE',
    timestamp: new Date().toUTCString(),
    plant: 1,
    machine: 2,
    reject_sum_percent: 0.034,
    reject_sum: 4,
    reject_factor: 0.003,
    picks: { cumulative_count: 522 },
    placements: { cumulative_count: 822 },
  },
  {
    nozzle_id: '1-FF',
    timestamp: new Date().toUTCString(),
    plant: 1,
    machine: 1,
    reject_sum_percent: 0.024,
    reject_sum: 2,
    reject_factor: 0.04,
    picks: { cumulative_count: 101 },
    placements: { cumulative_count: 102 },
  },
];
