export default [
  {
    timestamp: new Date().toUTCString(),
    nozzle_id: 'N-1',
    plant: '1',
    machine: 'PM1',
    reject_sum_percent: 0.034,
    reject_sum: 1,
    reject_factor: 0.05,
    poss_missing: 1,
    comp_missing: 2,
    type: '1240',
    picks: { cumulative_count: 133 },
    placements: { cumulative_count: 833 },
    optel_schedule_wo: '4010405712T',
    side: 'Top',
  },
  {
    timestamp: new Date().toUTCString(),
    nozzle_id: 'N-12',
    plant: '1',
    machine: 'PM2',
    reject_sum_percent: 0.014,
    reject_sum: 3,
    reject_factor: 0.02,
    poss_missing: 1,
    comp_missing: 2,
    type: '1240',
    picks: { cumulative_count: 133 },
    placements: { cumulative_count: 833 },
    optel_schedule_wo: '4010405712T',
    side: 'Top',
  },
  {
    timestamp: new Date().toUTCString(),
    nozzle_id: 'N-2',
    plant: '2',
    machine: 'PM3',
    reject_sum_percent: 0.044,
    reject_sum: 4,
    reject_factor: 0.06,
    poss_missing: 1,
    comp_missing: 2,
    type: '1240',
    picks: { cumulative_count: 133 },
    placements: { cumulative_count: 833 },
    optel_schedule_wo: '4010405712T',
    side: 'Top',
  },
  {
    timestamp: new Date().toUTCString(),
    nozzle_id: 'N-14',
    plant: '10',
    machine: 'PM1',
    reject_sum_percent: 0.034,
    reject_sum: 4,
    reject_factor: 0.003,
    poss_missing: 1,
    comp_missing: 2,
    type: '1240',
    picks: { cumulative_count: 522 },
    placements: { cumulative_count: 822 },
    optel_schedule_wo: '4010405712T',
    side: 'Top',
  },
  {
    timestamp: new Date().toUTCString(),
    nozzle_id: 'N-3',
    plant: '20',
    machine: 'PM2',
    reject_sum_percent: 0.024,
    reject_sum: 2,
    reject_factor: 0.04,
    poss_missing: 1,
    comp_missing: 2,
    type: '1240',
    picks: { cumulative_count: 101 },
    placements: { cumulative_count: 102 },
    optel_schedule_wo: '4010405712T',
    side: 'Top',
  },
];
