version: '3'

services:
  ui:
    image: ra-demo-ui
    environment:
    - PK_HOST=7e36a7e0-a3f4-46f0-8f8a-4213762cb593.pubkeeper.nio.works
    - PK_PORT=443
    - PK_SECURE=true
    - PK_JWT=2da90cdcd8019517436fccd045d595ee24b70936b2344efa066638cd518cff3c
    - WS_HOST=7e36a7e0-a3f4-46f0-8f8a-4213762cb593.websocket.nio.works
    - WS_PORT=443
    - WS_SECURE=true
    ports:
    - 3000:80
